services:
  - type: web
    name: asics-alert-bot
    runtime: python
    pythonVersion: 3.11.9
    buildCommand: ""
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: true
      - key: CHAT_ID
        sync: true
